import { db } from '../../../utils/db';
import { customerTasks, customerActivities, customerRetentionProfiles, customers, enquiries, users } from '../../../database/schema';
import { eq, and } from 'drizzle-orm';

export default defineEventHandler(async (event) => {
  const dealerId = event.context.dealerId;
  const userId = event.context.userId;
  const body = await readBody(event);

  if (!dealerId) {
    throw createError({ statusCode: 401, message: 'Unauthorized' });
  }

  // Validate required fields
  if (!body.title || !body.dueDate) {
    throw createError({
      statusCode: 400,
      message: 'Title and due date are required',
    });
  }

  if (!body.customerId && !body.enquiryId) {
    throw createError({
      statusCode: 400,
      message: 'Either customerId or enquiryId is required',
    });
  }

  // Tenancy guards: every linked record and the assignee must belong to this dealer.
  if (body.customerId) {
    const c = await db.query.customers.findFirst({
      where: and(eq(customers.id, body.customerId), eq(customers.dealerId, dealerId)),
      columns: { id: true },
    });
    if (!c) throw createError({ statusCode: 404, message: 'Customer not found' });
  }
  if (body.enquiryId) {
    const e = await db.query.enquiries.findFirst({
      where: and(eq(enquiries.id, body.enquiryId), eq(enquiries.dealerId, dealerId)),
      columns: { id: true },
    });
    if (!e) throw createError({ statusCode: 404, message: 'Enquiry not found' });
  }
  if (body.assignedTo) {
    const u = await db.query.users.findFirst({
      where: and(eq(users.id, body.assignedTo), eq(users.dealerId, dealerId)),
      columns: { id: true },
    });
    if (!u) throw createError({ statusCode: 400, message: 'Assignee is not a member of this dealer' });
  }

  // Create task
  const [newTask] = await db.insert(customerTasks).values({
    dealerId,
    customerId: body.customerId || null,
    enquiryId: body.enquiryId || null,
    title: body.title,
    description: body.description || null,
    taskType: body.taskType || 'follow_up',
    priority: body.priority || 'normal',
    dueDate: new Date(body.dueDate),
    dueTime: body.dueTime || null,
    reminderDate: body.reminderDate ? new Date(body.reminderDate) : null,
    assignedTo: body.assignedTo || userId,
    createdBy: userId,
    status: 'pending',
    isAutoGenerated: body.isAutoGenerated || false,
    automationRule: body.automationRule || null,
  }).returning();

  if (!newTask) {
    throw createError({
      statusCode: 500,
      message: 'Failed to create task',
    });
  }

  // Log activity if customer is associated
  if (body.customerId) {
    await db.insert(customerActivities).values({
      dealerId,
      customerId: body.customerId,
      enquiryId: body.enquiryId || null,
      taskId: newTask.id,
      activityType: 'note',
      activityDate: new Date(),
      subject: `Task Created: ${body.title}`,
      description: `Follow-up task scheduled for ${new Date(body.dueDate).toLocaleDateString()}`,
      createdBy: userId,
      isSystemGenerated: false,
    });

    // Update last contact date on retention profile
    await db.update(customerRetentionProfiles)
      .set({
        lastContactDate: new Date(),
        updatedAt: new Date(),
      })
      .where(and(
        eq(customerRetentionProfiles.customerId, body.customerId),
        eq(customerRetentionProfiles.dealerId, dealerId)
      ));
  }

  // Fetch created task with relations
  const taskWithRelations = await db.query.customerTasks.findFirst({
    where: eq(customerTasks.id, newTask.id),
    with: {
      customer: {
        columns: {
          id: true,
          firstName: true,
          lastName: true,
          email: true,
        },
      },
      assignedUser: {
        columns: {
          id: true,
          firstName: true,
          lastName: true,
        },
      },
    },
  });

  return {
    success: true,
    task: taskWithRelations,
  };
});
