import type { DealerStudioLeadPayload, DealerStudioSettings } from './types';

export function buildDealerStudioSandboxLead(
  settings: DealerStudioSettings,
  dealerId: string,
  now = new Date(),
): DealerStudioLeadPayload {
  const marker = `${dealerId.slice(0, 8)}-${now.getTime()}`;
  return {
    lead: {
      name: 'SANDBOX Integration Test',
      first_name: 'SANDBOX',
      last_name: 'Integration Test',
      email: `dealer-studio-sandbox+${dealerId.slice(0, 8)}@bloodhyundai.com.au`,
      phone: '0400000000',
      message: `SANDBOX TEST — DO NOT CONTACT. Synthetic integration check generated by the Bloods Hyundai admin at ${now.toISOString()}.`,
      dealership_id: settings.sandboxDealershipId,
      category: 'General Enquiry',
      source: 'Website',
      location_id: settings.sandboxLocationId,
      provider: 'Bloods Hyundai Admin Sandbox',
      provider_id: `sandbox-${marker}`,
      user_email: settings.sandboxDefaultUserEmail || undefined,
      send_customer_email: false,
      fields: {
        sandbox_test: true,
        generated_at: now.toISOString(),
        dealer_id: dealerId,
      },
    },
  };
}
