import type { DealerStudioLeadPayload, DealerStudioSettings } from './types';

export function buildDealerStudioSandboxLead(
  settings: DealerStudioSettings,
  now = new Date(),
): DealerStudioLeadPayload {
  return {
    lead: {
      name: 'SANDBOX Integration Test',
      first_name: 'SANDBOX',
      last_name: 'Integration Test',
      email: 'dealer-studio-sandbox@bloodhyundai.com.au',
      phone: '0400000000',
      message: `SANDBOX TEST — DO NOT CONTACT. Synthetic integration check generated by the Bloods Hyundai admin at ${now.toISOString()}.`,
      dealership_id: settings.sandboxDealershipId,
      category: 'General Enquiry',
      source: 'Website',
      location_id: settings.sandboxLocationId,
      provider: 'Bloods Hyundai Admin Sandbox',
      provider_id: `sandbox-${now.getTime()}`,
      user_email: settings.sandboxDefaultUserEmail || undefined,
      send_customer_email: false,
      fields: {
        sandbox_test: true,
        generated_at: now.toISOString(),
      },
    },
  };
}
